server:
  servlet:
    context-path: '/graphql-web-mvc'

spring:
  threads:
    virtual:
      enabled: true
  graphql:
    path: "/graphql"
    graphiql:
      enabled: false
    schema:
      locations: "classpath:graphql/**/"
      printer:
        enabled: true
    cors:
      allowed-origin-patterns: "${CORS_ORIGINS_PATTERNS:http://localhost:*,http://127.0.0.1:*,https://*.example.com}"
      allowed-methods: "GET,POST"
      max-age: "1800s"