spring:
  threads:
    virtual:
      enabled: true
  graphql:
    path: "/graphql"
    cors:
      allowed-origins: "${CORS_ORIGINS:http://localhost:8080,http://127.0.0.1:8080}"
      allowed-methods: "GET,POST"
      max-age: "1800s"