server:
  servlet:
    context-path: '/graphql-web-mvc'

spring:
  threads:
    virtual:
      enabled: true
  graphql:
    path: "/graphql"
    graphiql:
      enabled: false
    schema:
      locations: "classpath:graphql/**/"
      printer:
        enabled: true
    cors:
      allowed-origin-patterns: "${CORS_ORIGINS_PATTERNS:http://localhost:*,http://127.0.0.1:*,https://*.example.com}"
      allowed-methods: "GET,POST"
      max-age: "1800s"

app:
  datasource:
    hikari:
      jdbc-url: "${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test-user}"
      username: "${APP_DATASOURCE_USERNAME:test-user}"
      password: "${APP_DATASOURCE_PASSWORD:test-password}"
      maximum-pool-size: "${APP_DATASOURCE_MAX_POOL_SIZE:30}"
      driver:
        class:
          name: "${APP_DATASOURCE_DRIVER_NAME:org.postgresql.Driver}"

tee:
  filter:
    enabled: "${TEE_FILTER_ENABLED:false}"

logging:
  level:
    web: INFO
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{x_request_id:-no_request_id} %m %wEx %n'